### ISSUE TITLE
Sorting bugs

### ISSUE THREAD

**Issue by Eruyome** [exiletrade/exiletrade#28] opened 2016-03-04 03:01 UTC
> Interesting. Speaking of which, the sorting is totally weird...
> If you sort by buyout/price, it goes as you would expect.
> When I sort by STAT though, it ignores the "gloves OR chest" bit.
> If I sort by highest cold res, for example, it will only show items of the same type as the one I clicked to > sort
> so if I sort by cold res by clicking a chest, I only get chests
> if I click gloves, only gloves.

**Comment by thirdy** [comment] 2016-03-04 06:36
This is caused by the fact that exiletools has the modifier contained in
itemtypes.

Possible solution to this might be sort via pseudo mods instead (or mods
total)

**Comment by Dominik-O22** [comment] 2016-03-04 09:31
pseudo mods would be the best, problem is that in most cases they are not available, but modsTotal, is available in all cases where  sorting makes sense

**Comment by Eruyome** [comment] 2016-04-20 10:44
Is this fixed?

**Comment by thirdy** [comment] 2016-04-20 12:50
We can close this ticket. Displaying the pseudo mod will let the user click
on it to sort.
Otherwise, I don't think this can be fixed on sorting on an explicit. It's
a limitation on exiletools.

**Closed as completed** 2016-04-20 13:44 UTC
Labels: enhancement
